# Generated by Django 5.2.3 on 2025-06-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='description_detail',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(max_length=100, verbose_name='Описание'),
        ),
    ]
