# Generated by Django 5.2.3 on 2025-07-22 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='webapp.project', verbose_name='Проект'),
            preserve_default=False,
        ),
    ]
