# Generated by Django 5.2.3 on 2025-07-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_issue_is_deleted_issue_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='summary',
            field=models.CharField(max_length=50, verbose_name='Краткое описание'),
        ),
    ]
