# Generated by Django 5.2.3 on 2025-07-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_issue_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=65, verbose_name='Название'),
        ),
    ]
